---
AWSTemplateFormatVersion: 2010-09-09
Description: Template de deploiement d'une instance de Notebook

Parameters:
  NotebookName:
    Description: Name of the notebook
    Type: String
  RoleArnName:
    Description: Name of the notebook
    Type: String
  SubnetId:
    Description: Subnet of the instance
    Type: String
  SgId:
    Description: Security Group
    Type: String

Resources:
  MyNotebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties: 
      DirectInternetAccess: "Disabled"
      InstanceType: "ml.t2.medium"
      NotebookInstanceName: !Ref NotebookName
      RoleArn: !Ref RoleArnName
      RootAccess: "Enabled"
      SecurityGroupIds: 
        - !Ref SgId
      SubnetId: !Ref SubnetIds

Outputs:
  MyNotebook:
    Value: !Ref MyNotebook
    Description: Name the instance deployed